# Generated by Django 6.0.4 on 2026-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_restaurant_email_restaurant_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
