# Generated by Django 6.0.4 on 2026-05-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.restaurant",
            ),
        ),
    ]
